<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Installer\Module'                        => __DIR__ . '/Module.php',
    'Installer\Controller\InstallerController' => __DIR__ . '/src/Installer/Controller/InstallerController.php',
    'InstallerTest\Framework\TestCase'        => __DIR__ . '/tests/Installer/Framework/TestCase.php',
    'InstallerTest\SampleTest'                => __DIR__ . '/tests/Installer/SampleTest.php',
);
